name: Mr MikesPizza
favicon: null
layout_spectrum: 0.624818371143192
typography_spectrum: 0.500119931763038
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.09771386906504631
  lightness: 0.7051388237159699
  saturation: 0.41081711067818105
  rhythmicContrast: 0.14115992025472224
purpose: []
